name       : python-multidict
version    : 6.0.4
release    : 4
source     :
    - https://github.com/aio-libs/multidict/archive/refs/tags/v6.0.4.tar.gz : 5d1441b0b0cf18aa11a8e564996775b6c4ca0e99dcd4147c515b2cb7345b0a84
license    : Apache-2.0
component  : programming.python
summary    : The multidict implementation
description: |
    Multidict is dict-like collection of key-value pairs where key might occur more than once in the container.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
