name       : python-multidict
version    : 4.5.2
release    : 3
source     :
    - https://github.com/aio-libs/multidict/archive/v4.5.2.tar.gz : 09be72d0c223be82aa5ed42766665048c329dba9f4440cd2b9633f78e12b28da
license    : Apache-2.0
component  : programming.python
summary    : Multidict is dict-like collection of key-value pairs where key might
    be occurred more than once in the container.
description: |
    Multidict is dict-like collection of key-value pairs where key might be occurred more than once in the container.
builddeps  :
    - cython
build      : |
    %python3_setup
install    : |
    %python3_install
